name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Snapcraft
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Snapcraft Snap
        id: build-snapcraft
        uses: snapcore/action-build@v1

      - name: Upload snapcraft snap
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.build-snapcraft.outputs.snap }}

      - name: Verify snapcraft snap
        run: |
          sudo snap install --dangerous --classic ${{ steps.build-snapcraft.outputs.snap }}

  integration-spread-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        spread-jobs:
          - google:ubuntu-16.04-64
          - google:ubuntu-18.04-64
          - google:ubuntu-20.04-64

    steps:
      - name: Checkout snapcraft
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download snapcraft snap
        uses: actions/download-artifact@v2
        with:
          name: snap

      - name: Install spread
        run: curl -s https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz | sudo tar xzv -C /usr/bin

      - name: Run spread
        run: spread ${{ matrix.spread-jobs }}
