name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Snapcraft
        uses: actions/checkout@v2
        with:
          # Fetch all of history so Snapcraft can determine its own version from git.
          fetch-depth: 0

      - name: Build Snapcraft Snap
        id: build-snapcraft
        uses: snapcore/action-build@v1

      - name: Upload Snapcraft Snap
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.build-snapcraft.outputs.snap }}

      - name: Verify Snapcraft Snap
        run: |
          # Make sure it is installable.
          sudo snap install --dangerous --classic ${{ steps.build-snapcraft.outputs.snap }}


  static-tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Install Snapd
        run: |
          sudo chown root:root /
          sudo apt update
          sudo apt install -y snapd
          sudo snap wait system seed.loaded

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libyaml-dev python3-yaml python3.6-dev
          sudo snap install core
          sudo snap install core18
          sudo snap install shellcheck
          sudo snap install black --channel beta --devmode

      - name: Install LXD
        run: |
          sudo apt remove -y lxd lxd-client
          sudo groupadd --force --system lxd
          sudo usermod --append --groups lxd $USER
          sudo snap install lxd
          sudo lxd waitready --timeout=30
          sudo lxd init --auto

      - name: Install Snapcraft snap
        run: |
          sudo snap install --dangerous --classic snapcraft_*.snap

      - name: Checkout Snapcraft
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python dependencies
